name: flake8

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 --max-line-length 120 --extend-ignore E203,E501 --show-source --count
