name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install black

      - name: Run black
        run: black --line-length 120 --verbose .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formating changes made by linter

