name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run black
      - uses: psf/black@stable
        with:
          options: "--line-length 120 --diff --verbose"

      - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply black changes

