name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        run: pip install black flake8 ; black --line-length 120 --diff --verbose .

      - uses: stefanzweifel/git-auto-commit-action@v4

